charitydonation/charitydonation/urls.py
from django.contrib import admin
from django.urls import path
from donationapp.views import LandingPage, AddDonation, Login, Register, UserView
from donationapp import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", LandingPage.as_view(), name="landing-page"),
    path("add-donation/", AddDonation.as_view(), name="add-donation"),
    path("login/", Login.as_view(), name="login"),
    path("register/", Register.as_view(), name="register"),
    path("logout/", views.logout_view, name="logout"),
    path("user/<int:pk>/", UserView.as_view(), name="user-view"),
]

charitydonation/donationapp/models.py
from django.contrib.auth.models import User
from django.db import models
from phone_field import PhoneField
from django.utils.translation import gettext as _


class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Institution(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField()

    class Type(models.TextChoices):
        FOUNDATION = "FD", _("foundation")
        NGO = "NG", _("non-governmental organization")
        LOCAL_FUNDRAISING = "LF", _("local fundraising")

    type = models.CharField(choices=Type.choices, default=Type.FOUNDATION, max_length=2)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name


class Donation(models.Model):
    quantity = models.PositiveSmallIntegerField()
    categories = models.ManyToManyField(Category)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    address = models.CharField()
    phone_number = PhoneField(blank=True, help_text=_("Contact phone number"))
    city = models.CharField(max_length=32)
    zip_code = models.CharField(max_length=5)
    pick_up_date = models.DateField(auto_now_add=True)
    pick_up_time = models.TimeField(auto_now_add=True)
    pick_up_comment = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.address

charitydonation/donationapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext as _


class RegistrationForm(forms.ModelForm):
    name = forms.CharField(max_length=100)
    surname = forms.CharField(max_length=100)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            "name",
            "surname",
            "email",
            "password",
            "password2",
        ]
        labels = {
            "name": "Imię",
            "surname": "Nazwisko",
            "email": "E-mail",
            "password": "Hasło",
            "password2": "Powtórz hasło",
        }


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)


class DonationForm(forms.Form):
    quantity = forms.IntegerField()
    address = forms.CharField(max_length=128)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=128)
    zip_code = forms.CharField(max_length=6)
    pick_up_date = forms.DateField(widget=forms.DateInput(attrs={'placeholder': 'RRRR-MM-DD'}))
    pick_up_time = forms.TimeField(widget=forms.TimeInput(attrs={'placeholder': '--:--'}))
    pick_up_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': '5'}), required=False)

charitydonation/donationapp/views.py
from typing import Any, Dict
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView

from .forms import RegistrationForm, LoginForm, DonationForm
from .models import Donation, Institution, Category


class LandingPage(View):
    def get(self, request):
        total_bags = Donation.objects.count()
        supported_orgs = Institution.objects.count()
        foundations = Institution.objects.filter(type__icontains="FD")
        ngos = Institution.objects.filter(type__icontains="NG")
        local_fundraisings = Institution.objects.filter(type__icontains="LF")
        context = {
            "total_bags": total_bags,
            "supported_orgs": supported_orgs,
            "foundations": foundations,
            "ngos": ngos,
            "local_fundraisings": local_fundraisings,
        }
        return render(request, "index.html", context)


class AddDonation(LoginRequiredMixin, View):
    login_url = reverse_lazy("login")
    redirect_field_name = "next"

    def get(self, request):
        categories = Category.objects.all()
        institutions = Institution.objects.all()
        form = DonationForm()
        return render(request, 'form.html',
                      {'categories': categories, 'institutions': institutions, 'form': form})

    def post(self, request):
        form = DonationForm(request.POST)
        categories = request.POST['categories']
        institution = request.POST['institution']
        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            address = form.cleaned_data['address']
            city = form.cleaned_data['city']
            zip_code = form.cleaned_data['zip_code']
            phone_number = form.cleaned_data['phone_number']
            pick_up_date = form.cleaned_data['pick_up_date']
            pick_up_time = form.cleaned_data['pick_up_time']
            pick_up_comment = form.cleaned_data['pick_up_comment']
            user = request.user.id
            donation = Donation.objects.create(quantity=quantity, institution_id=institution, address=address,
                                               city=city, zip_code=zip_code, phone_number=phone_number,
                                               pick_up_date=pick_up_date, pick_up_time=pick_up_time,
                                               pick_up_comment=pick_up_comment, user_id=user)
            donation.categories.add(categories)
            return render(request, 'form-confirmation.html')
        else:
            categories = Category.objects.all()
            institutions = Institution.objects.all()
            return render(request, 'form.html',
                          {'categories': categories, 'institutions': institutions, 'form': form})


class Login(View):
    def get(self, request):
        form = LoginForm()
        return render(request, "login.html", {"form": form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                return redirect("landing-page")
            else:
                return redirect("register")
        return render(request, "login.html", {"form": form})


class Register(View):
    def get(self, request):
        form = RegistrationForm()
        return render(request, "register.html", {"form": form})

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            name = form.cleaned_data["name"]
            surname = form.cleaned_data["surname"]
            username = email  # Przyjmowanie emaila jako nazwy użytkownika
            user = User.objects.create_user(
                username=username, email=email, password=password
            )
            user.first_name = name
            user.last_name = surname
            user.save()
            return redirect("login")
        return render(request, "register.html", {"form": form})


def logout_view(request):
    logout(request)
    return redirect("landing-page")


class UserView(ListView):
    model = Donation
    template_name = "user_page.html"

    def get_queryset(self):
        queryset = Donation.objects.filter(user=self.request.user)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = User.objects.filter(id=self.request.user.id)
        return context

charitydonation/donationapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Charity Donation App</title>
    <script src="{% static "js/app.js" %}"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
  </head>
  <body>

{% block content %}
{% endblock content %}

<footer>
      <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50">
            <input type="text" name="name" placeholder="Imię" />
          </div>
          <div class="form-group form-group--50">
            <input type="text" name="surname" placeholder="Nazwisko" />
          </div>

          <div class="form-group">
            <textarea
              name="message"
              placeholder="Wiadomość"
              rows="1"
            ></textarea>
          </div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2019</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"
            ><img src="{% static "images/icon-facebook.svg" %}"
          /></a>
          <a href="#" class="btn btn--small"
            ><img src="{% static "images/icon-instagram.svg" %}"
          /></a>
        </div>
      </div>
    </footer>
  </body>
</html>

charitydonation/donationapp/templates/form-confirmation.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <body>
    {% include "login_links.html" %}

      <div class="slogan container container--90">
          <h2>
            Dziękujemy za przesłanie formularza. Na maila prześlemy wszelkie
            informacje o odbiorze.
          </h2>
      </div>
    </header>
{% endblock content %}


charitydonation/donationapp/templates/form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% include "login_links.html" %}

    <div class="slogan container container--90">
        <div class="slogan--item">
            <h1>
                Oddaj rzeczy, których już nie chcesz<br />
                <span class="uppercase">potrzebującym</span>
            </h1>

            <div class="slogan--steps">
                <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
                <ul class="slogan--steps-boxes">
                    <li>
                        <div><em>1</em><span>Wybierz rzeczy</span></div>
                    </li>
                    <li>
                        <div><em>2</em><span>Spakuj je w worki</span></div>
                    </li>
                    <li>
                        <div><em>3</em><span>Wybierz fundację</span></div>
                    </li>
                    <li>
                        <div><em>4</em><span>Zamów kuriera</span></div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    </header>

    <section class="form--steps">
        <div class="form--steps-instructions">
            <div class="form--steps-container">
                <h3>Ważne!</h3>
                <p data-step="1" class="active">
                    Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
                    wiedzieć komu najlepiej je przekazać.
                </p>
                <p data-step="2">
                    Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
                    wiedzieć komu najlepiej je przekazać.
                </p>
                <p data-step="3">
                    Wybierz jedną, do
                    której trafi Twoja przesyłka.
                </p>
                <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
            </div>
        </div>

        <div class="form--steps-container">
            <div class="form--steps-counter">Krok <span>1</span>/5</div>

            <form id="donation-form" method="post">
                {% csrf_token %}
                <!-- STEP 1: class .active is switching steps -->
                <div data-step="1" class="active">
                    <h3>Zaznacz co chcesz oddać:</h3>

                    {% for category in categories %}
                        <div class="form-group form-group--checkbox">
                            <label>
                                <input
                                        type="checkbox"
                                        name="categories"
                                        value="{{ category.pk }}"
                                />
                                <span class="checkbox radio"></span>
                                <span class="description"
                                >{{ category.name }}</span
                                >
                            </label>
                        </div>
                    {% endfor %}

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>

                <!-- STEP 2 -->
                <div data-step="2">
                    <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

                    <div class="form-group form-group--inline">
                        <label>
                            Liczba 60l worków:
                            <input type="text" name="quantity" value="{{ form.quantity.value }}">
                        </label>
                    </div>

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>

                <!-- STEP 3 -->
                <div data-step="3">
                    <h3>Wybierz organizacje, której chcesz pomóc:</h3>

                    {% for institution in institutions %}
                        <div class="form-group form-group--checkbox">
                            <label>
                                <input type="radio" name="institution" value="{{ institution.pk }}"
                                       class="{% for category in institution.categories.all %}{{ category.pk }} {% endfor %}"/>
                                <span class="checkbox radio"></span>
                                <span class="description">
                                    <div class="title">{{ institution.get_type_display }} {{ institution.name }}</div>
                                    <div class="subtitle">Cel i misja: {{ institution.description }}</div>
                                </span>
                            </label>
                        </div>
                    {% endfor %}

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>

                <!-- STEP 4 -->
                <div data-step="4">
                    <h3>Podaj adres oraz termin odbioru rzeczy przez kuriera:</h3>

                    <div class="form-section form-section--columns">
                        <div class="form-section--column">
                            <h4>Adres odbioru</h4>
                            <div class="form-group form-group--inline">
                                <label>Ulica</label>
                                <input type="text" name="address">
                            </div>

                            <div class="form-group form-group--inline">
                                <label>Miasto</label>
                                <input type="text" name="city">
                            </div>

                            <div class="form-group form-group--inline">
                                <label>Kod pocztowy</label>
                                <input type="text" name="zip_code">
                            </div>

                            <div class="form-group form-group--inline">
                                <label>Numer telefonu</label>
                                <input type="text" name="phone_number">
                            </div>
                        </div>

                        <div class="form-section--column">
                            <h4>Termin odbioru</h4>
                            <div class="form-group form-group--inline">
                                <label>Data</label>
                                <input type="date" name="pick_up_date">
                            </div>

                            <div class="form-group form-group--inline">
                                <label>Godzina</label>
                                <input type="time" name="pick_up_time">
                            </div>

                            <div class="form-group form-group--inline">
                                <label>Uwagi dla kuriera</label>
                                <textarea name="pick_up_comment" rows="5"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step" onclick="confirmDonation()">Dalej</button>
                    </div>
                </div>
            </form>

            <!-- STEP 5 -->
            <div id="summary-step" data-step="5" style="display: none;">
                <h3>Podsumowanie Twojej darowizny</h3>

                <div class="summary">
                    <div class="form-section">
                        <h4>Oddajesz:</h4>
                        <ul>
                            <li>
                                <span class="icon icon-bag"></span>
                                <span class="summary--text" id="summary-quantity"></span>
                            </li>
                            <li>
                                <span class="icon icon-hand"></span>
                                <span class="summary--text" id="summary-institution"></span>
                            </li>
                        </ul>
                    </div>

                    <div class="form-section form-section--columns">
                        <div class="form-section--column">
                            <h4>Adres odbioru:</h4>
                            <ul>
                                <li id="summary-address"></li>
                                <li id="summary-city"></li>
                                <li id="summary-zip-code"></li>
                                <li id="summary-phone-number"></li>
                            </ul>
                        </div>

                        <div class="form-section--column">
                            <h4>Termin odbioru:</h4>
                            <ul>
                                <li id="summary-pick-up-date"></li>
                                <li id="summary-pick-up-time"></li>
                                <li id="summary-pick-up-comment"></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="form-group form-group--buttons">
                    <button type="button" class="btn prev-step" onclick="goToStep(4)">Wstecz</button>
                    <button type="button" class="btn" onclick="submitForm()">Potwierdzam</button>
                </div>
            </div>
        </div>
    </section>

    <script src="{% static 'js/donation_script.js' %}"></script>
{% endblock content %}

charitydonation/donationapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <body>
    <header class="header--main-page">
      <nav class="container container--70">
          {% if user.is_authenticated %}

        <ul class="nav--actions">
          <li class="logged-user">
            Witaj {{ request.user }}
            <ul class="dropdown">
              <li><a href="{% url "user-view" %}">Profil</a></li>
              <li><a href="#">Ustawienia</a></li>
              <li><a href="{% url "logout" %}">Wyloguj</a></li>
            </ul>
          </li>
        </ul>
        {% else %}
        <ul class="nav--actions">
          <li><a href={% url 'login' %} class="btn btn--small btn--without-border">Zaloguj</a></li>
          <li><a href={% url 'register' %} class="btn btn--small btn--highlighted">Załóż konto</a></li>
        </ul>
        {% endif %}
        <ul>
          <li><a href="" class="btn btn--without-border active">Start</a></li>
          <li><a href="#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a href={% url 'add-donation' %} class="btn btn--without-border">Przekaż dary</a></li>
          <li><a href="#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>

      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Zacznij pomagać!<br />
            Oddaj niechciane rzeczy w zaufane ręce
          </h1>
        </div>
      </div>
    </header>

    <section id="stats" class="stats">
      <div class="container container--85">
        <div class="stats--item">
          <em>{{ total_bags }}</em>
          <h3>Oddanych worków</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum tempora!</p>
        </div>

        <div class="stats--item">
          <em>{{ supported_orgs }}</em>
          <h3>Wspartych organizacji</h3>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate quas quam.</p>
        </div>

      </div>
    </section>

    <section id="steps" class="steps">
      <h2>Wystarczą 4 proste kroki</h2>

      <div class="steps--container">
        <div class="steps--item">
          <span class="icon icon--hands"></span>
          <h3>Wybierz rzeczy</h3>
          <p>ubrania, zabawki, sprzęt i inne</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--arrow"></span>
          <h3>Spakuj je</h3>
          <p>skorzystaj z worków na śmieci</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--glasses"></span>
          <h3>Zdecyduj komu chcesz pomóc</h3>
          <p>wybierz zaufane miejsce</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--courier"></span>
          <h3>Zamów kuriera</h3>
          <p>kurier przyjedzie w dogodnym terminie</p>
        </div>
      </div>

      <a href={% url 'register' %} class="btn btn--large">Załóż konto</a>
    </section>

    <section id="about-us" class="about-us">
      <div class="about-us--text">
        <h2>O nas</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt libero optio esse quisquam illo omnis.</p>
        <img src="{% static "images/signature.svg" %}" class="about-us--text-signature" alt="Signature" />
      </div>
      <div class="about-us--image"><img src="{% static "images/about-us.jpg" %}" alt="People in circle" /></div>
    </section>

     <section id="help" class="help">
      <h2>Komu pomagamy?</h2>

      <ul class="help--buttons">
        <li data-id="1"><a href="#" class="btn btn--without-border active">Fundacjom</a></li>
        <li data-id="2"><a href="#" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
        <li data-id="3"><a href="#" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
      </ul>

      <!-- SLIDE 1 -->
      <div class="help--slides active" data-id="1">
        <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym się zajmują, komu pomagają i czego potrzebują.</p>

        {% for foundation in foundations %}
        <ul class="help--slides-items">
          <li>
            <div class="col">
              <div class="title">Fundacja {{ foundation.name }}</div>
              <div class="subtitle">Cel i misja: {{ foundation.description }}</div>
            </div>

            <div class="col"><div class="text">Fundacja</div></div>
          </li>
            {% endfor %}
        </ul>
        <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
        </ul>
        -->
      </div>


      <!-- SLIDE 2 -->
      <div class="help--slides" data-id="2">
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic officiis mollitia dolor, neque aspernatur accusamus debitis. Ducimus, officia. Quia, sunt illum! Non iste placeat ab ipsum alias
          quos suscipit corporis!
        </p>
        {% for ngo in ngos %}
        <ul class="help--slides-items">
          <li>
            <div class="col">
              <div class="title">{{ ngo.name }}</div>
              <div class="subtitle">{{ ngo.description }}</div>
            </div>

            <div class="col"><div class="text">Organizacja pozarządowa</div></div>
          </li>
          {% endfor %}

        <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="4">4</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="5">5</a></li>
        </ul>
        -->
      </div>

      <!-- SLIDE 3 -->
      <div class="help--slides" data-id="3">
        <p>Lorem ipsum dolor sit amet, his ocurreret persequeris ea, ad utinam laudem duo. Verterem adipisci partiendo eos ne, ea his reque quaeque recteque, ne quo lobortis intellegam.</p>
        {% for local_fundraising in local_fundraisings %}
          <ul class="help--slides-items">
          <li>
            <div class="col">
              <div class="title">{{ local_fundraising.name }}</div>
              <div class="subtitle">{{ local_fundraising.description }}</div>
            </div>

            <div class="col"><div class="text">Lokalna zbiórka</div></div>
          </li>
          {% endfor %}

        <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
        </ul>
        -->
      </div>
    </section>
{% endblock content %}

charitydonation/donationapp/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <body>
    <header>
      <nav class="container container--70">
        <ul class="nav--actions">
          <li><a href="#">Zaloguj</a></li>
          <li class="highlighted"><a href={% url 'register' %}>Załóż konto</a></li>
        </ul>
          {% include 'menu_links.html' %}
      </nav>
    </header>

    <section class="login-page">
      <h2>Zaloguj się</h2>
      <form method="post" action="{% url 'login' %}">
          {% csrf_token %}
        <div class="form-group">
          <input type="email" name="email" placeholder="Email" />
        </div>
        <div class="form-group">
          <input type="password" name="password" placeholder="Hasło" />
          <a href="#" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
        </div>

        <div class="form-group form-group--buttons">
          <a href="{% url 'register' %}" class="btn btn--without-border">Załóż konto</a>
          <button class="btn" type="submit">Zaloguj się</button> 
        </div>
      </form>
    </section>
  {% endblock content %}

charitydonation/donationapp/templates/user_page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<body>
    {% include "login_links.html" %}
        <ul>
          <li><a href="" class="btn btn--without-border active">Start</a></li>
          <li><a href="#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a href={% url 'add-donation' %} class="btn btn--without-border">Przekaż dary</a></li>
          <li><a href="#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>
    </header>
    <div class="slogan--item">
        <h2>Imię: {{ user.first_name }}</h2>
        <h2>Nazwisko: {{ user.last_name }}</h2>
        <h2>E-mail: {{ user.email }}</h2>
    </div>
    <div class="slogan--item">
        <h2>Twoje dary</h2>
        {% for donation in donation_list %}
        <li>Ilość worków: {{ donation.quantity }}</li>
        <li>Organizacja: {{ donation.institution }}</li>
        <li>Kategoria: {{ donation.categories }}</li>
        <li>Data oddania: {{ donation.pick_up_date }}</li>
        <li>Godzina oddania: {{ donation.pick_up_time }}</li>
        <li>Komentarz: {{ donation.pick_up_comment }}</li>
        {% endfor %}
    </div>
</body>
{% endblock content %}